version: '3'

services:
  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - ./:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A core beat -l info
    volumes:
      - ./:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]
    depends_on:
      - redis

  smtp-server:
    image: mailhog/mailhog
    expose:
      - 1025
      - 8025
    ports:
      - '1025:1025'
      - '8025:8025'

  flower:
    build: .
    command: /usr/src/app/entrypoint.sh
    environment:
      - DJANGO_SERVICE=flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery