# Generated by Django 4.2.3 on 2023-07-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_task_date_alter_task_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default='2023-07-03'),
        ),
    ]
