# Generated by Django 4.2.7 on 2024-06-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_task_date_historicaltask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltask",
            name="date",
            field=models.DateField(default="2024-06-22"),
        ),
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateField(default="2024-06-22"),
        ),
    ]
