# Generated by Django 5.0.6 on 2024-06-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_historicaltask_date_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='date',
            field=models.DateField(default='2024-06-26'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default='2024-06-26'),
        ),
    ]
